language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcurl4-openssl-dev
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.add("HTTPClient"); Pkg.add("JSON"); Pkg.build("Connect"); Pkg.test("Connect"; coverage=true)'
